import os
from notion_client import AsyncClient
from worker.config import config
import logging

logger = logging.getLogger(__name__)

class NotionService:
    def __init__(self):
        self.token = config.NOTION_TOKEN
        if not self.token:
            logger.warning("NOTION_TOKEN not found. Notion integration will fail.")
        self.client = AsyncClient(auth=self.token)

    async def create_page(self, parent_page_id: str, title: str, markdown_content: str) -> str:
        """
        Creates a new page in Notion under the parent_page_id.
        Returns the URL of the created page.
        """
        if not self.token:
            raise ValueError("NOTION_TOKEN is missing")

        try:
            # 1. Create Page
            new_page = await self.client.pages.create(
                parent={"page_id": parent_page_id},
                properties={
                    "title": [
                        {
                            "text": {
                                "content": title
                            }
                        }
                    ]
                },
                # We can try to convert markdown to blocks here, 
                # but for MVP maybe just putting it in a code block or simple text?
                # Notion API doesn't accept raw markdown directly as content.
                # We need a Markdown-to-Blocks converter.
                # For simplicity in this step, let's just add a text block.
                children=[
                    {
                        "object": "block",
                        "type": "paragraph",
                        "paragraph": {
                            "rich_text": [
                                {
                                    "type": "text",
                                    "text": {
                                        "content": "Content generated by FlashNote AI (Markdown support coming soon):\n\n" + markdown_content[:2000] # Truncate
                                    }
                                }
                            ]
                        }
                    }
                ]
            )
            return new_page["url"]
        except Exception as e:
            logger.error(f"Failed to create Notion page: {e}")
            raise

notion_service = NotionService()
